# FROM azul/zulu-openjdk:8
# #RUN addgroup -S spring && adduser -S spring -G spring
# RUN groupadd -r spring && useradd -r spring -g spring
# USER spring:spring
# ARG JAR_FILE=build/libs/*.jar
# COPY ${JAR_FILE} app.jar
# ENTRYPOINT ["java", "-Dspring.profiles.active=dev", "-jar","/app.jar"]


# Use the openjdk image as the base for the first stage
FROM gradle:jdk8 AS build
COPY . /app
WORKDIR /app
RUN gradle build --no-daemon

FROM openjdk:8-jre-alpine
WORKDIR /app
RUN addgroup -S spring && adduser -S spring -G spring 
COPY --from=build /app/build/libs/*.jar /app/app.jar
#CMD ["java", "-jar", "myapp.jar"]
ENTRYPOINT ["java", "-Dspring.profiles.active=dev", "-jar","/app/app.jar"]